<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1cca6e58-3e03-4291-a55a-6171bf187282</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" Version="8.3.5" />
    <PackageReference Include="DotNetCore.CAP.Dashboard" Version="8.3.5" />
    <PackageReference Include="DotNetCore.CAP.InMemoryStorage" Version="8.3.5" />
    <PackageReference Include="DotNetCore.CAP.Kafka" Version="8.3.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

</Project>
