<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>736942d5-5af9-4289-b847-2ae4da4e6bc0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="DotNetCore.CAP" Version="8.4.0" />
	<PackageReference Include="DotNetCore.CAP.Dashboard" Version="8.4.0" />
	<PackageReference Include="DotNetCore.CAP.InMemoryStorage" Version="8.4.0" />
	<PackageReference Include="DotNetCore.CAP.Kafka" Version="8.4.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
